project_name: resto

env:
  - CGO_ENABLED=0

release:
  prerelease: auto
  draft: true
  name_template: "Resto v{{ .Version }}"

before:
  hooks:
    - go mod tidy

builds:
  - binary: bin/resto
    ldflags:
      - -X main.version=v{{ .Version }}
      - -X main.versionDate={{ .Env.VersionDate }}

    goos:
      - darwin
      - linux
      - windows

    goarch:
      - 386
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

archives:
  - id: nix
    builds: [ macos, linux ]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Os }}_v{{ .Version }}_{{ .Arch }}"

    wrap_in_directory: "true"
    replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE

  - id: windows
    builds: [ windows ]
    <<: *archive_defaults
    wrap_in_directory: "false"
    format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT
    maintainer: abdfnx
    homepage: https://github.com/abdfnx/resto
    bindir: /usr
    file_name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Arch }}"
    description: a CLI app can send pretty HTTP & API requests with TUI
    formats:
      - apk
      - deb
      - rpm

brews:
  - goarm: 6
    tap:
      owner: abdfnx
      name: homebrew-tap
    commit_author:
      name: "abdfnx"
      email: "{{ .Env.Email }}"
    homepage: "https://github.com/abdfnx/resto"
    description: "a CLI app can send pretty HTTP & API requests with TUI"

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
