project_name: resto

release:
  prerelease: auto
  draft: true
  name_template: "Resto v{{ .Version }}"

before:
  hooks:
    - go mod tidy

builds:
  - <<: &build_defaults
      binary: bin/resto
      main: ./
      ldflags:
        - -X main.version=v{{ .Version }}
        - -X main.versionDate={{ .Env.VersionDate }}

    id: macos
    goos: [ darwin ]
    goarch: [ amd64 ]

  - <<: *build_defaults
    id: linux
    goos: [ linux ]
    goarch: [ amd64 ]

    env:
      - CGO_ENABLED=0

  - <<: *build_defaults
    id: windows
    goos: [ windows ]
    goarch: [ amd64 ]

archives:
  - id: nix
    builds: [ macos, linux ]
    <<: &archive_defaults
      name_template: "{{ .ProjectName }}_{{ .Os }}_v{{ .Version }}_{{ .Arch }}"

    wrap_in_directory: "true"
    replacements:
      darwin: macos
    format: zip
    files:
      - LICENSE

  - id: windows
    builds: [ windows ]
    <<: *archive_defaults
    wrap_in_directory: "false"
    format: zip
    files:
      - LICENSE

nfpms:
  - license: MIT
    maintainer: abdfnx
    homepage: https://github.com/abdfnx/resto
    bindir: /usr
    file_name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Arch }}"
    description: send pretty HTTP & API requests from your terminal with GUI.
    formats:
      - deb
      - rpm
