name: Build

on:
  workflow_dispatch:
    inputs:
      versionDate:
        description: "Version Date"
        required: true

env:
  VERSION_DATE: ${{ github.event.inputs.versionDate }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --timeout 500
        env:
          GITHUB_TOKEN: ${{ github.token }}
          VersionDate: ${{ env.VERSION_DATE }}

      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: resto
          path: dist/*
