name: Release

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ github.token }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up `Go`
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up `GoReleaser`
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: Set up `Tag`
        id: ghtag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up `Date`
        run: go run ./build/date.go >> date.txt

      - name: Build
        run: VersionDate="$(cat date.txt)" Email="${{ secret.AUTHOR_EMAIL }}" goreleaser release --rm-dist --timeout 100m

      # - name: Build `gh-resto`
      #   env:
      #     TAG: ${{ steps.ghtag.outputs.tag }}
      #   run: |
      #     DATE="$(cat date.txt)"
      #     gh repo clone abdfnx/gh-resto
      #     cd gh-resto
      #     ./build.sh $TAG $DATE
      #     ls -a dist

      # - name: Upload files
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     repository: abdfnx/gh-resto
      #     draft: true
      #     files: |
      #       gh-resto/dist/darwin-x86_64
      #       gh-resto/dist/linux-i386
      #       gh-resto/dist/linux-x86_64
      #       gh-resto/dist/windows-i386
      #       gh-resto/dist/windows-x86_64

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Resto Containers
        run: |
          make brc
          make bfrc
